
services:
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile.multi
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      MYSQL_URL: jdbc:mysql://mysqlserver/petclinic
    volumes:
      - /app

  mysqlserver:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    volumes:
      - mysql_config:/etc/mysql/conf.d

  redis-0:
    image: redis:4.0.2
    volumes:
      - ./redis/redis-0:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-1:
    image: redis:4.0.2
    volumes:
      - ./redis/redis-1:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-2:
    image: redis:4.0.2
    volumes:
      - ./redis/redis-2:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  sentinel-1:
    image: redis:4.0.2
    volumes:
      - ./redis/sentinel-01:/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]

  sentinel-2:
    image: redis:4.0.2
    volumes:
      - ./redis/sentinel-02:/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]

  sentinel-3:
    image: redis:4.0.2
    volumes:
      - ./redis/sentinel-03:/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]

volumes:
  mysql_config:

